"""Make room_id nullable in ReservationEntity

Revision ID: be837d80f1dd
Revises: 81ad65728b64
Create Date: 2025-05-02 15:13:37.982425

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be837d80f1dd"
down_revision = "81ad65728b64"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "academics__section_room_room_id_fkey",
        "academics__section_room",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "academics__section_room",
        "room",
        ["room_id"],
        ["id"],
        referent_schema="public",
    )
    op.alter_column(
        "coworking__reservation", "room_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint(
        "coworking__reservation_room_id_fkey",
        "coworking__reservation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "coworking__reservation",
        "room",
        ["room_id"],
        ["id"],
        referent_schema="public",
    )
    op.drop_constraint(
        "coworking__seat_room_id_fkey", "coworking__seat", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "coworking__seat", "room", ["room_id"], ["id"], referent_schema="public"
    )
    op.drop_constraint("office_hours_room_id_fkey", "office_hours", type_="foreignkey")
    op.create_foreign_key(
        None, "office_hours", "room", ["room_id"], ["id"], referent_schema="public"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "office_hours", type_="foreignkey")
    op.create_foreign_key(
        "office_hours_room_id_fkey", "office_hours", "room", ["room_id"], ["id"]
    )
    op.drop_constraint(None, "coworking__seat", type_="foreignkey")
    op.create_foreign_key(
        "coworking__seat_room_id_fkey", "coworking__seat", "room", ["room_id"], ["id"]
    )
    op.drop_constraint(None, "coworking__reservation", type_="foreignkey")
    op.create_foreign_key(
        "coworking__reservation_room_id_fkey",
        "coworking__reservation",
        "room",
        ["room_id"],
        ["id"],
    )
    op.alter_column(
        "coworking__reservation", "room_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_constraint(None, "academics__section_room", type_="foreignkey")
    op.create_foreign_key(
        "academics__section_room_room_id_fkey",
        "academics__section_room",
        "room",
        ["room_id"],
        ["id"],
    )
    # ### end Alembic commands ###
