"""Add timezone to created_at column

Revision ID: ff8c95f5b461
Revises: be837d80f1dd
Create Date: 2025-05-02 20:00:23.588551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff8c95f5b461'
down_revision = 'be837d80f1dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('academics__section_room_room_id_fkey', 'academics__section_room', type_='foreignkey')
    op.create_foreign_key(None, 'academics__section_room', 'room', ['room_id'], ['id'], referent_schema='public')
    op.alter_column('conversation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint('coworking__reservation_room_id_fkey', 'coworking__reservation', type_='foreignkey')
    op.create_foreign_key(None, 'coworking__reservation', 'room', ['room_id'], ['id'], referent_schema='public')
    op.drop_constraint('coworking__seat_room_id_fkey', 'coworking__seat', type_='foreignkey')
    op.create_foreign_key(None, 'coworking__seat', 'room', ['room_id'], ['id'], referent_schema='public')
    op.drop_constraint('office_hours_room_id_fkey', 'office_hours', type_='foreignkey')
    op.create_foreign_key(None, 'office_hours', 'room', ['room_id'], ['id'], referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'office_hours', type_='foreignkey')
    op.create_foreign_key('office_hours_room_id_fkey', 'office_hours', 'room', ['room_id'], ['id'])
    op.drop_constraint(None, 'coworking__seat', type_='foreignkey')
    op.create_foreign_key('coworking__seat_room_id_fkey', 'coworking__seat', 'room', ['room_id'], ['id'])
    op.drop_constraint(None, 'coworking__reservation', type_='foreignkey')
    op.create_foreign_key('coworking__reservation_room_id_fkey', 'coworking__reservation', 'room', ['room_id'], ['id'])
    op.alter_column('conversation', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'academics__section_room', type_='foreignkey')
    op.create_foreign_key('academics__section_room_room_id_fkey', 'academics__section_room', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###
